### ISSUE TITLE
[Bug] Lainchan - Error, post was not made

### ISSUE THREAD

**Issue by seniorm0ment** [Adamantcheese/Kuroba#1107]
When posting on Lainchan, when sending it provides a generic error. However once the refresh happens your post actually went through, although it doesn't mark it as your post also.

**Comment by Adamantcheese** [comment]
Duplicate of #598 and #814 probably? This seems to have been a problem in the past at the very least.

**Comment by seniorm0ment** [comment]
Possibly, they didn't provide much info. Posting technically works, but it errors and doesn't show it sent but it actually did.

Also worth noting external Lainchan links don't open in Kuroba. No issues with 4ch links

**Comment by Adamantcheese** [comment]
Just want to make sure, but was it a specific board? Or is this issue resolved? I did see a banner message saying some posting issue was fixed. I did try to post on Lainchan's /r/ and I had no errors at all, posts fine and marks your post correctly. The external links thing I already have a fix for, but I'd like to bundle up fixes if possible for the site.

**Comment by seniorm0ment** [comment]
Just checked, it errors still for me, only tested on the technology board.

**Comment by Adamantcheese** [comment]
I really appreciate the information. I've fixed that posting issue which I suspect is still in Clover (using an encoded URL path rather than unencoded wasn't matching things correctly), and I've added in those external links (just were missing from the manifest) and I also noticed that pages come free with Vichan's catalog so I implemented those as well. Have fun on Lainchan!
