### ISSUE TITLE
Importing settings breaks app

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#208]
I can no longer open the app after I imported my settings from v4.4.4 Kuroba? No info on why it happens, only fix is to clear all app data.

I also notice a small spelling error in the import warning the word "LOSE."

**Comment by K1rakishou** [comment]
Just tried the same and it worked normally. Can you, maybe, provide the settings file? Though, if you have a passcode entered or something like this you should probably remove it from the file first. Look for the "preference_pass_token", "preference_pass_pin" and "preference_pass_id" strings, then just replace them with some random values.

**Comment by K1rakishou** [comment]
Well, yes, there was a bug with exporting/importing of the loadables, where wrong id would be used when importing them. I guess it might possibly cause crashes in some cases. Should be fixed in #206

**Comment by K1rakishou** [comment]
I'm closing this because the fix was already merged and released.

**Comment by ownBard** [comment]
Alright, sorry for being unresponsive for a bit. I tested again and I'm still having this issue in v4.5.2 but only with my settings file from v4.4.4 as you said. I'll try to post it as soon as I can.

edit: Nevermind, the file was completely borked for some reason. I'm just gonna give up.
